### ISSUE TITLE
Empty api_user parameter

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-sendgrid#1]
Setting up initial sendgrid notification and experiencing issues sending api_user to sendgrid.

Step 1. Add Sendgrid rule
Step 2. From the drop down inside in the integration, select username and enter data.
Step 3. Add api_key from dropdown. (api_key is the same as password)
Step 4. Save and send test lead. api_key is populated but username / (api_user) is not.

### 

Request:

POST /api/mail.send.json HTTP/1.1
Accept: application/json
Content-Length: 193
Content-Type: application/x-www-form-urlencoded
Host: sendgrid.com
X-Mailer: LeadConduit

api_user=&
api_key[removed]
&to=
&from=
&subject=
&toname=test%20test
&fromname=Sendgrid%20notification%20for%20Bank%20of%20KC
&bcc=karalyn%40activeprospect.com
&text=You%20have%20a%20new%20lead!

Response:
{message: "error", errors: ["Permission denied, wrong credentials"]}

**Comment by zalary** [comment]
this should be resolved as of Version 1.0.1
