### ISSUE TITLE
change to get credentials from environment

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-sendgrid#10]
Remove the request variables `api_user` and `api_key`, and instead have them set from the process environment (as in the [TowerData integration](https://github.com/activeprospect/leadconduit-integration-towerdata/blob/master/src/outbound.coffee#L23)). 

These events would then also have the `billable` flag set to true. 

This would allow customers to send email without exposing our credentials, or making us [bend over backwards to hide them](https://activeprospect.slack.com/archives/support/p1422990482000538).

**Comment by zalary** [comment]
There is a somewhat unique issue here with using env vars which is that each user should really use their own subaccount because send grid has the idea of reputation. If we use the same keys for everyone and someone blows up our rep with spam everyone suffers the consequences. We should definitely think of a better easier way to handle this though.

**Comment by cgrayson** [comment]
Ah, I see. That does complicate things. :-) 

Perhaps solving two different "send email" cases with two different integrations would make this simpler: call them "deliver lead" and "send to consumer", say. 

The first, "deliver lead", is like what Classic can do, and could be used in the case under discussion today with client services. I think that one could use our regular credentials from the environment, as there should never be spam/deliverability problems there. 

The second, "send to consumer" (or "auto-responder"), is the one where those should be segmented off in case of reputation-damaging activity. That one would require credentials provided in the flow configuration. 

But I think they're both still billable, regardless. (I suppose there's a case where someone might have their own SendGrid account and credentials. That could be solved by a third variation, maybe, but I suggest we ignore that case for now.)

**Comment by zalary** [comment]
yes, I like that implementation suggestion.  Segmenting those would even allow us to help in guiding the mapping/templating for each.

**Comment by zalary** [comment]
this is now done for the 'lead-delivery' integration.  hopefully we can switch current users to this new integration and phase out the other one, and deal with the trickier use-cases in the future

**Comment by cgrayson** [comment]
Cool. Since making an autoresponder integration would be a new issue, I think this one is now as closed as it's going to get, don't you?

**Comment by zalary** [comment]
agreed!
