### ISSUE TITLE
Remove 'send' integration

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-sendgrid#23]
The 'send' integration is VERY problematic for several reasons, the 2 worst offenders being:

1. it reveals usernames and passwords for sendgrid accounts (in most cases, APs)
2. it allows the user to send anything they want in the body to anybody they want (this could compromise our account's reputation, making it impossible to send emails in the future)

**Comment by alexj** [comment]
Is this the Sendgrid integration or an alternate integration that uses SendGrid?

**Comment by zalary** [comment]
there are 2 integrations in this integration (I don't know what words to use) 'send' and 'lead delivery'  we really need to get people off of 'send' and onto 'lead delivery'

**Comment by poppop51** [comment]
So we are not going to offer an in-house auto-responder capability? Somebody better tell sales.

**Comment by alexj** [comment]
Thanks Zal. We plan to a new integration for sending confirmations, whitelabelling SendGrid for it. For now, please do not pull out the 'send' functionality for now. We do need to eliminate exposure of our user/pass info.

**Comment by zalary** [comment]
We are working on it, which is why we need to know what all people are using it for.  Right now, the problem is that if we get one bad user who autospams a userlist, they could literally ruin our entire account.

**Comment by zalary** [comment]
and while it's all fine while it's fine, this could be a huge problem if we had multiple accounts actually using it as an autoresponder in production and our reputation plummeted.  We would NOT be able to recover from that easily.

**Comment by alexj** [comment]
Fully understand the impact to deliverability and reputation if someone spams using SG. Is there a pressing reason why this needs to be done right now over other priorities, beyond the risk that this might happen?

**Comment by poppop51** [comment]
Just an FYI, the new client who would be using this in LCN is an unknown (to us), Tax Defense Network.

**Comment by zalary** [comment]
@alexj can we grab a few minutes to chat about this one

**Comment by alexj** [comment]
Definitely. I'll come by in a bit for us to discuss.

**Comment by poppop51** [comment]
SG user: MeadJohnson: (LCC) sends every lead an email with an opt-out link to our proprietary offerconfirmation.com.
SG user: Meredith American Baby: (LCC) sends every lead an email with an opt-out link to our proprietary offerconfirmation.com.
These are the only current users I can recall atm.

**Comment by zalary** [comment]
This change should not affect anyone using LCC.   As I said, it's not that we are not planning to support auto-responder functionality, it's that there are some technical hurdles we haven't cleared in doing so yet.

**Comment by poppop51** [comment]
Gotcha. Except insofar as as migrating these to LCN is affected.

**Comment by zalary** [comment]
I feel like there are several reasons beyond this integration that preclude them from being good candidates for migration right now, but if this is blocking, definitely let us know.   (I know Meredith has an auto-returns script that runs through FTP and LCC that would be blocking as well).

**Comment by poppop51** [comment]
Agreed, just providing info for ya. It's not blocking right now.

**Comment by cgrayson** [comment]
A new, SES-backed [autoresponder integration](https://github.com/activeprospect/leadconduit-integration-autoresponder) is finished & in production. Can this removal of the `send` integration proceed now?

**Comment by cgrayson** [comment]
Just commented on #25, suggesting there that `lead_delivery` is the one that should get axed, and then I find this issue, that says `send` is the bad one. :worried: Someone straighten me out. :smiley: 

`lead_delivery` uses our credentials, and offers the `to` address as mappable in the flow, while `send` requires the user's credentials and doesn't offer `to` mapping. So it seems to me like `lead_delivery` is the one where our SG account would have more exposure to abuse & reputation issues, right?

**Comment by zalary** [comment]
I guess at some point we just have to trust our users to do whatever they are going to do.  If they want to put their username and password in an open text box, that's ok.  I do think we should get to a point where make sure no one is using our credentials still and that we retire any passwords that have been revealed in users accounts to this point.  Then, let the monkey go bananas. :)

That said, I don't think the send integration was built particularly well and there are some confusing mapping that could be cleaned up, so imosho we should
    1. make sure no one is using 'lead delivery' and if they are, move them to SES
    2. delete 'lead delivery'
    3. do our best to make sure no one is using our credentials, if so make them stop.
    4. clean 'send' up (if we wanted to go the extra mile we could configure the integration to use their new [actual api keys](https://sendgrid.com/docs/Classroom/Send/api_keys.html) instead of username/password credentials )
    5. profit?! (oh sorry, that should have been step 3)

**Comment by cgrayson** [comment]
> If they want to put their username and password in an open text box, that's ok.

This happens in lots of integrations, but as long as the integration variables are of type `credential` – as they are in `send`, here – then they should be masked in lead details and safe, I think? 

Here's a sample from a production `lead_delivery` lead detail: `...api_user=******************&api_key=**************&to=support@activeprospect.com&toname=Support&from=no-reply@activeprospect.com&fromname=LeadConduit Lead Delivery&subj...`

> 1. make sure no one is using 'lead delivery' and if they are, move them to SES
> 2. delete 'lead delivery'

Covered by #25. 

> (3) do our best to make sure no one is using our credentials, if so make them stop.

Unless I'm misunderstanding you, I don't think this is necessary, see my `credential` masking comment above.

> (4) clean 'send' up (if we wanted to go the extra mile we could configure the integration to use their new actual api keys instead of username/password credentials )

Let's have separate issues for this, as needed. Is the "extra mile/actual api keys" part the same as in #22? 

> (5) profit?! (oh sorry, that should have been step 3)

![](http://www.stopcallsgetcash.com/wp-content/uploads/2014/10/phone-cash.png)

**Comment by cgrayson** [comment]
>> (3) do our best to make sure no one is using our credentials, if so make them stop.
> 
> Unless I'm misunderstanding you, I don't think this is necessary

Followup after discussion elsewhere: there was a time when our own credentials were mapped in the `send` integration in customer flows, so though masked in lead detail, they could be seen in the flow config. I searched the database this afternoon and found the only uses of `send` are in our own accounts (AP, AP Demo, client-services test accounts).

**Comment by cgrayson** [comment]
Closing; I think the various items in this issue are either decided-against (#wontfix) or documented in other issues.
