### ISSUE TITLE
Correct from in UI

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-sendgrid#4]
Please change the value and label of fromname to from. This breaks the integration as is. 

It will work if you manually enter from.

**Comment by zalary** [comment]
We shouldn't remove fromname, but we do need in from to the request vars.

**Comment by kcaponeAP** [comment]
Sorry, just the label then perhaps. In the POST to send grid, it is stated as from (&from=noreply%40activeprospect.com). There is no mention of fromname in anywhere else in the customer facing UI so it's confusing.

**Comment by zalary** [comment]
this should be resolved as of Version 1.0.1
