### ISSUE TITLE
Extra data in SendGrid POST

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-sendgrid#5]
Account: Karalyn Test
Flow: NBOKC Test Leads
URL: https://next.leadconduit.com/events/54b8394e2d333bf82e0dc7d6?event_id=54b8394e2d333bf82e0dc7d7

Issue: I didn't include toname in my SendGrid steps, yet it is added in the POST data. 

SendGrid Step: http://screencast.com/t/a0twqWaekvG
POST data: http://screencast.com/t/UGFL01MbQh

PII omitted

**Comment by zalary** [comment]
In this case, the integration automatically tries to populate the `to` field with {{lead.email}} and the `toname` field with the title, first name and/or last name.   The only way to override that would be to set an outbound mapping for the sendgrid delivery to map those fields to no value 

We are working on clarifying what will be sent via an integration to make this sort of situation less confusing.
